config/routes.rb
Rails.application.routes.draw do
  resources :notes

  root "notes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
  validates :name, presence: true

  default_scope {order("notes.created_at DESC")}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = Note.all
  end

  def show
  end

  def new
    @note = Note.new
  end

  def create
    @notes = Note.all
    @note = Note.new(note_params)

    if @note.save
      respond_to do |format|
        format.html { redirect_to root_path, notice: "Note was successfully created." }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to root_path, notice: "Note was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Note destroyed!" }
      format.turbo_stream
    end
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasyNote</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <!-- Font Awesome 6 -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

  <!-- Font -->
  <link href="https://fonts.cdnfonts.com/css/ubuntu" rel="stylesheet">

  <!-- FAV AND ICONS   -->
  <%= favicon_link_tag "favicon.png" %>

  <body class="bg-gray-100 dark:bg-slate-900 max-w-full overflow-x-hidden font-['ubuntu']">
    <%= render "shared/header" %>
    <main class="min-h-screen p-4 md:p-12 w-[80%] mx-auto my-12 bg-gray-200 rounded-2xl shadow-lg shadow-gray-700">
      <%= yield %>
    </main>
    <%= render "shared/footer" %>
    <%= javascript_include_tag "preline" %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= simple_form_for note, html: { class: "note form" } do |f| %>
  <% if note.errors.any? %>
    <div class="error-message">
      <%= note.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <%= f.input :name, input_html: { autofocus: true } %>
  <%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/notes/_note.html.erb
<!-- Icon Blocks -->
<div class="max-w-[85rem] px-4 pb-10 mx-auto">
  <div class="grid sm:grid-cols-1 lg:grid-cols-2 items-center gap-6 md:gap-10">
    <% @notes.each do |note| %>
      <%= turbo_frame_tag note do %>
        <!-- Card -->
        <div class="w-full h-full bg-red-100 shadow-lg rounded-lg p-5 dark:bg-slate-900 hover:shadow-gray-800">
          <div class="min-h-[70%]">
            <p class="pb-4">
              <i class="fa-solid fa-thumbtack text-red-900"></i>
              <%= link_to note.name, note_path(note), data: { turbo_frame: "_top" } %>
            </p>
          </div>
          <div class="flex px-5 mb-10">
            <div class="flex-auto">
              <%= button_to "", note_path(note), method: :delete, class: "fa-solid fa-trash-can text-lg text-red-700 inline-flex justify-center items-center w-[2.5rem] h-[2.5rem] rounded-full border-4 border-red-300 bg-red-200 shadow-lg hover:shadow-gray-800 hover:border-red-800" %>
            </div>
            <div class="flex-auto text-end">
              <%= link_to "", edit_note_path(note), method: :delete, class: "fa-solid fa-pen-to-square text-lg text-red-700 w-[2.5rem] h-[2.5rem] rounded-full border-4 border-red-300 bg-red-200 text-center py-[0.4rem] shadow-lg hover:shadow-gray-800 hover:border-red-800" %>
            </div>
          </div>
        </div>
        <!-- End Card -->
      <% end %>
    <% end %>
  </div>
</div>
<!-- End Icon Blocks -->

app/views/notes/create.turbo_stream.erb
<%= turbo_stream.prepend "notes", partial: "notes/note", locals: { note: @note } %>
<%= turbo_stream.update Note.new, "" %>

app/views/notes/destroy.turbo_stream.erb
<%= turbo_stream.remove @note %>

app/views/notes/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to note"), note_path(@note) %>

  <div class="header">
    <h1>Edit note</h1>
  </div>

  <<%= turbo_frame_tag @note do %>
    <%= render "form", note: @note %>
  <% end %>
</main>

app/views/notes/index.html.erb
<main class="p-2 lg:p-10">
  <%= turbo_frame_tag "first_turbo_frame" do %>
    <div class="flex bg-gray-50 mb-10 px-10 py-4 rounded-full shadow-md hover:shadow-gray-800 h-[3.7rem]">
      <div class="flex-auto">
        <span class="font-bold text-lg md:text-xl lg:text-3xl text-gray-800">Notes</span>
      </div>
      <div class="flex-auto text-end">
        <%= link_to "Add note", new_note_path, class: "btn btn-primary hover:btn-primary-hover lg:btn-lg", data: { turbo_frame: dom_id(Note.new) } %>
      </div>
    </div>
  <% end %>
  <%= turbo_frame_tag Note.new %>

  <%= turbo_frame_tag "notes" do %>
    <%= render "note" %>
  <% end %>
</main>

app/views/notes/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to notes"), notes_path %>

  <div class="header">
    <h1>New note</h1>
  </div>

  <%= turbo_frame_tag @note do %>
    <%= render "form", note: @note %>
  <% end %>
</main>

app/views/notes/show.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to notes"), notes_path %>
  <div class="header">
    <h1>
      <%= @note.name %>
    </h1>
  </div>
</main>

app/views/shared/_footer.html.erb
<footer class="bg-gray-700">
  <div class="max-w-[85rem] py-10 px-4 sm:px-6 lg:px-8 mx-auto">
    <!-- Grid -->
    <div class="grid grid-cols-1 md:grid-cols-3 items-center gap-5 text-center">
      <div>
        <a class="inline-flex items-center gap-x-2 text-xl font-semibold text-gray-200" href="/">
          <%= image_tag "logo.png", class: "w-10 h-auto hover:opacity-75" %>
          EasyNote
        </a>
      </div>
      <!-- End Col -->

      <ul class="text-center">
        <li class="inline-block relative pr-8 last:pr-0 last-of-type:before:hidden before:absolute before:top-1/2 before:right-3 before:-translate-y-1/2 before:content-['/'] before:text-gray-300 dark:before:text-gray-600">
          <a class="inline-flex gap-x-2 text-sm text-gray-400 hover:text-gray-50 dark:text-gray-500 dark:hover:text-gray-200" href="#">
            About Us
          </a>
        </li>
        <li class="inline-block relative pr-8 last:pr-0 last-of-type:before:hidden before:absolute before:top-1/2 before:right-3 before:-translate-y-1/2 before:content-['/'] before:text-gray-300 dark:before:text-gray-600">
          <a class="inline-flex gap-x-2 text-sm text-gray-400 hover:text-gray-50 dark:text-gray-500 dark:hover:text-gray-200" href="#">
            Our Services
          </a>
        </li>
        <li class="inline-block relative pr-8 last:pr-0 last-of-type:before:hidden before:absolute before:top-1/2 before:right-3 before:-translate-y-1/2 before:content-['/'] before:text-gray-300 dark:before:text-gray-600">
          <a class="inline-flex gap-x-2 text-sm text-gray-400 hover:text-gray-50 dark:text-gray-500 dark:hover:text-gray-200" href="#">
            Contact Us
          </a>
        </li>
      </ul>
      <!-- End Col -->

      <!-- Social Brands -->
      <div class="md:text-right space-x-2">
        <a class="inline-flex justify-center items-center w-8 h-8 text-center text-gray-300 hover:text-gray-500 hover:bg-gray-100 rounded-full focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-offset-2 focus:ring-offset-white transition dark:text-gray-500 dark:hover:text-gray-200 dark:hover:bg-gray-800 dark:focus:ring-offset-slate-900" href="#">
          <svg class="w-3.5 h-3.5" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
            <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
          </svg>
        </a>
        <a class="inline-flex justify-center items-center w-8 h-8 text-center text-gray-300 hover:text-gray-500 hover:bg-gray-100 rounded-full focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-offset-2 focus:ring-offset-white transition dark:text-gray-500 dark:hover:text-gray-200 dark:hover:bg-gray-800 dark:focus:ring-offset-slate-900" href="#">
          <svg class="w-3.5 h-3.5" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
            <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
          </svg>
        </a>
        <a class="inline-flex justify-center items-center w-8 h-8 text-center text-gray-300 hover:text-gray-500 hover:bg-gray-100 rounded-full focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-offset-2 focus:ring-offset-white transition dark:text-gray-500 dark:hover:text-gray-200 dark:hover:bg-gray-800 dark:focus:ring-offset-slate-900" href="#">
          <i class="fa-brands fa-linkedin"></i>
        </a>
      </div>
      <!-- End Social Brands -->
    </div>
    <!-- End Grid -->
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="flex flex-wrap sm:justify-start sm:flex-nowrap z-50 w-full bg-white text-sm py-4 dark:bg-gray-800">
  <nav class="max-w-[85rem] w-full mx-auto px-4 sm:flex sm:items-center sm:justify-between" aria-label="Global">
    <div class="flex items-center justify-between">
      <a class="inline-flex items-center gap-x-2 text-xl font-semibold dark:text-white" href="/">
        <%= image_tag "logo.png", class: "w-10 h-auto hover:opacity-75" %>
        EasyNote
      </a>
      <div class="sm:hidden">
        <button type="button" class="hs-collapse-toggle p-2 inline-flex justify-center items-center gap-2 rounded-md border font-medium bg-white text-gray-700 shadow-sm align-middle hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-white focus:ring-blue-600 transition-all text-sm dark:bg-slate-900 dark:hover:bg-slate-800 dark:border-gray-700 dark:text-gray-400 dark:hover:text-white dark:focus:ring-offset-gray-800" data-hs-collapse="#navbar-image-and-text-2" aria-controls="navbar-image-and-text-2" aria-label="Toggle navigation">
          <svg class="hs-collapse-open:hidden w-4 h-4" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
          </svg>
          <svg class="hs-collapse-open:block hidden w-4 h-4" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
            <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
          </svg>
        </button>
      </div>
    </div>
    <div id="navbar-image-and-text-2" class="hs-collapse hidden overflow-hidden transition-all duration-300 basis-full grow sm:block">
      <div class="flex flex-col gap-5 mt-5 sm:flex-row sm:items-center sm:justify-end sm:mt-0 sm:pl-5">
        <a class="font-medium text-blue-500" href="/" aria-current="page">Home</a>
        <a class="font-medium text-gray-600 hover:text-gray-400 dark:text-gray-400 dark:hover:text-gray-500" href="#">Our Services</a>
        <a class="font-medium text-gray-600 hover:text-gray-400 dark:text-gray-400 dark:hover:text-gray-500" href="#">About Us</a>
        <a class="font-medium text-gray-600 hover:text-gray-400 dark:text-gray-400 dark:hover:text-gray-500" href="#">Contact Us</a>
      </div>
    </div>
  </nav>
</header>